# Generated by Django 6.0.3 on 2026-03-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='topic',
            new_name='title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question_count',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
