# Generated by Django 6.0.3 on 2026-03-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_user_quiz_created_by_rename_topic_quiz_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=5),
        ),
    ]
