# Generated by Django 6.0.3 on 2026-03-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='status',
            field=models.CharField(default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
