# Generated by Django 6.0.3 on 2026-03-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_quizattempt_status_alter_quizattempt_total_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
